version: '1.1'
services:
  mysql:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
      - ./data-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  node-app:
    build: ./gate-simulator  # собираем образ из Dockerfile в каталоге gate-simulator
    image: gate-simulator:1.0
    ports:
      - '9999:9999'